public class opportunity_productTriggerHandler {
	public static void beforeInsert(List<opportunity_product_Amount_calculation__c>triggerNew,Map<Id,opportunity_product_Amount_calculation__c>triggerNewMap,List<opportunity_product_Amount_calculation__c>triggerOld,Map<Id,opportunity_product_Amount_calculation__c>triggerOldMap)
    {
	}
    public static void beforeUpdate(List<opportunity_product_Amount_calculation__c>triggerNew,Map<Id,opportunity_product_Amount_calculation__c>triggerNewMap,List<opportunity_product_Amount_calculation__c>triggerOld,Map<Id,opportunity_product_Amount_calculation__c>triggerOldMap)
    {  
         
	}
}